### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/tsujan/featherpad/) for Tsujan/FeatherPad.

### CODE REVIEW

**Comment by stefonarch** [comment]
I've reset the changes in weblate, so closing this should finish the thing. 
In featherpad I've locked the translations atm, there is a czechtranslation together with the french now so I can't reset it without loosing this.

**Comment by tsujan** [comment]
> there is a czech translation together with the french now

I'll merge it manually after closing this.

BTW, the mistake in the Hebrew translation has been repeated here. Although I'm closing this, it's strange.

**Comment by stefonarch** [comment]
I unlocked and resetted the changes in weblate.

**Comment by tsujan** [comment]
OK. Let's wait to see what will happen.

**Pull request closed without merging**
