### PR TITLE
Add support for NetBSD

### PR DESCRIPTION
**Pull request by voidpin**
Please allow building on NetBSD. Minor change required.
Built and running on my machine after minor patching.
Thx!

2020-01-23-112747_1366x768_scrot

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks but it should be added to other places too. Please search for `Q_OS_OPENBSD` in `x11.cpp` and `singleton.cpp` too and add ` || defined Q_OS_NETBSD` after it everywhere.

**Comment by voidpin** [comment]
Thanks! The first one was all I needed to build the package. But, I've followed your suggestion and added it everywhere.

**Comment by tsujan** [comment]
Thanks! Please tell me whether it works OK under NetBSD after these changes! I want to merge your PR.

**Comment by voidpin** [comment]
Yes, I've just re-built and installed the package. Its working perfectly.
I have one gtk-2 app left to go :)

**Comment by tsujan** [comment]
Excellent! I enjoy it whenever I see Linux and *BSD are so compatible with each other.

Merging...

**Comment by voidpin** [comment]
Thanks!
As long as it doesn't involve Linux specific things like `systemd`, `libudev`, `libinput`, ... its usually fine ;)

**Comment by tsujan** [comment]
> As long as it doesn't involve Linux specific things like systemd, libudev, libinput, ... its usually fine ;)

I avoid them in my apps.

I hope this compatibility will continue. The only thing that worries me is Wayland. It isn't very usable yet but if it becomes the default, I'll try to keep the X11 support.

**Comment by voidpin** [comment]
Wayland is getting a boost on NetBSD, thx to @niacat, see https://github.com/niacat/pkgsrc-wayland/blob/master/applications.md for a list of ready to use applications. Should be tried but, as long as one installs `qt5-qtwayland`, `featherpad` should just work ;)
This is also one of the reasons I want to get rid of gtk-2 apps ;)

**Comment by niacat** [comment]
Wouldn't it be easier and more portable to use Q_OS_UNIX here...?

**Comment by tsujan** [comment]
It's better to be added one by one because that shows it's tested.

**Comment by niacat** [comment]
Not really, it shows that someone tried to get it to build once. Unless you do continuous testing of this on GNU/HURD.

**Comment by tsujan** [comment]
> it shows that someone tried to get it to build once.

That's enough; less than it isn't.

As for me, I'm responsible for Linux, not other OS's. So, I'll add support for another OS if and only if a developer tests it once.

**Pull request merged**
