### PR TITLE
Update from Weblate

### PR DESCRIPTION
**Pull request by HelixBot**

### CODE REVIEW

**Comment by tsujan** [comment]
Thank you all!

@MaxiDvy 
"Caract. selec." is changed to "Selec. Caracteristicas" by Robert at https://github.com/tsujan/FeatherPad/pull/279/commits/0e6910fde06bae9881e2d85c9a34c4ea3c0c85e2 . Since Robert doesn't have a GitHub account, I can't call him. Can "Caracteristicas" be abbreviated too?

**Comment by tsujan** [comment]
@MaxiDvy Thanks for your reply!

> I think the better translate for this case is "Seleccionar caracteres" can be abbreviated "Selec. Caracteres"

I shouldn't interfere with translations, especially when my knowledge of the target language is minimal. Could you please correct it?

**Comment by MaxiDvy** [comment]
> @MaxiDvy Thanks for your reply!
> 
> > I think the better translate for this case is "Seleccionar caracteres" can be abbreviated "Selec. Caracteres"
> 
> I shouldn't interfere with translations, especially when my knowledge of the target language is minimal. Could you please correct it?

I have corrected it in weblate, when I get some time I will check the translations of other users, if you have any doubts about any in particular do not hesitate to contact me.

**Comment by tsujan** [comment]
Thank you very much!

**Comment by MaxiDvy** [comment]
@tsujan I was using and testing the application to better understand the context of certain options and descriptions, and not make a simple text translation without understanding the context, I could see that it was not well translated that way.
So I corrected it again to be understood well in spanish, I also reviewed all the other translations of FeatherPad and enriched some descriptions to make them look more professional and explanatory for the inexperienced user, It could be said that FeatherPad at this moment is decently translated into spanish.
I hope not to bother with such abrupt changes in some cases.

**Comment by tsujan** [comment]
@MaxiDvy Excellent job!

**Pull request merged**
