### PR TITLE
Add a help file translated into Japanese.(help_ja_JP)

### PR DESCRIPTION
**Pull request by FuRuYa7**
FeatherPad/featherpad/data/help_ja_JP

1. "help_ja_JP" is the Japanese version of the help file.
By replacing "help" with "help_ja_JP", Japanese help will be available.

2. The description of commonly used shortcuts is at the top.

Description example that "Japanese help can be used"
---

日本語環境において、「help」を「help_ja_JP」に置き換えることで、日本語のヘルプを利用できます。  
In Japanese environment, you can use Japanese help by replacing "help" with "help_ja_JP".  
  
Ubuntu での操作例:  
$ cd /usr/share/featherpad  
$ sudo mv help help-En  
$ sudo cp help_ja_JP help

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks for the hard work but I'm afraid the Help doc isn't translatable technically -- there's no way to show different Helps with different languages because it's a simple text file.

I intentionally made the Help doc this way to not bother translators with a long text that may be changed frequently. The GUI -- and especially the Preferences dialog -- has informative tooltips that guide the user.

That being said, I'll add the common shortcuts to a translatable dialog in future and will copy/paste your translation for it; opened this issue: https://github.com/tsujan/FeatherPad/issues/219

**Comment by tsujan** [comment]
Never mind! I found a way of adding *optional* translated Help docs like this and showing them automatically. No need to an additional shortcut dialog. Will add a commit and a few lines to `README.md` later.

Merged.

**Comment by FuRuYa7** [comment]
Thank you for thinking a lot.

Personally I am thankful that the current help document is a simple text file. I can edit it by myself, it can display with write-protected. I can display it immediately with "Ctrl+H".

If I want to do, I can write not only personal memos but also frequently used strings, and it can be used for pasting on text. These things are personal usage, so I did not introduce them.

**Comment by tsujan** [comment]
A translated Help was your good idea. At first, I saw it impossible but that was only because I hadn't thought about it. Each translator could have his/her separate Help and FeatherPad will show it when used with the language in question. If a language doesn't have a Help, the English Help will be shown.

Currently, I'm busy with fixing some issues in FeatherNotes; I'll make the Help translatable after that.

**Pull request merged**
