### PR TITLE
Add Haiku support

### PR DESCRIPTION
**Pull request by khallebal**
Hi @tsujan,
I have created a patch for haiku, if you would be kind enough to accept, please if there is anything you don't like or want to rearrange let me know.
BTW, did you get the time to read my reply on #185?
Regards.

### CODE REVIEW

**Comment by khallebal** [comment]
Cool, thanks for all your help.
I have 2 feature requests, shall i create new issues for them?

1. the ability to add new themes (something similar to that of FocusWriter, i very much like that feature)

1. The ability to customize the syntax highlighting with more colors than just the existing ones (something similar to what Pe in haiku has, open Pe in haiku and take look in the preferences)

Regards.

**Comment by tsujan** [comment]
Apps like FocusWriter contradict platform integration. I strongly prefer not to add hard-coded styles to my apps, so that they are styled only by the active Qt style plugin (or style engine). At least in Linux, that means platform integration. In other places, `App -style STYLE_PLUGIN` can be used or, better, the environment variable `QT_STYLE_OVERRIDE` can be set. Of course, that requires installing some Qt style plugins.

As for customized syntax highlighting, please read https://github.com/tsujan/FeatherPad/issues/145#issuecomment-388578820

**Comment by tsujan** [comment]
BTW, days ago, I read somewhere that a Qt style plugin is made for Haiku, so that Qt apps look native under it. Unfortunately I don't remember its name but you might be more familiar with these things.

**Comment by khallebal** [comment]
From #145 

> So, I have no plan for syntax color customization yet. However, I should think about a plan at some point.

Fair enough.

> Apps like FocusWriter contradict platform integration.

Well, actually the "theme" term here is somewhat misleading in FocusWriter, as it doesn't change the aspect of the interface at all, it merely adds some customizations to the text area, and sorry if i offended you by mentionning that app, it wasn't intentional.

> BTW, days ago, I read somewhere that a Qt style plugin is made for haiku.

Yes it's called qthaikuplugins, it's still WIP but already usable.
https://github.com/threedeyes/qthaikuplugins
Regards.

**Comment by tsujan** [comment]
>  and sorry if i offended you by mentionning that app

You didn't at all. Maybe the word "strongly" in my comment made you think so. It has a history. As the author of [Kvantum](https://github.com/tsujan/Kvantum/tree/master/Kvantum), I've encountered so many broken/bad hard-coded styles and added so many workarounds for them. I have nothing against developers' choices as far as they are correct and, in the case of FocusWriter, they are so.

Being a member of the LXQt theme, I just have a strong preference for a uniform look and feel, as far as possible.

> Yes it's called qthaikuplugins, it's still WIP but already usable.

I might add a Haiku theme to Kvantum at some point, although I don't think Kvantum can be compiled on Haiku.

**Comment by tsujan** [comment]
> Yes it's called qthaikuplugins, it's still WIP but already usable.

Thanks! It may be good reference for me to see how I could make Kvantum compilable on Haiku :)

**Comment by tsujan** [comment]
Merged. Thanks again for your contribution!

**Comment by khallebal** [comment]
> Thanks! It may be good reference for me to see how I could make Kvantum compilable on Haiku :)
It would be cool to have all the Kvantum's themes in haiku, when you decide to take shot at it let me know so we collaborate on it.
you can reach me at khallebal at gmail dot com.
Thanks again for reviewing and merging.
ps: I may add soon another patch to complete the haiku support.

**Comment by tsujan** [comment]
> I may add soon another patch to complete the haiku support.

Feel free to add anything needed. I'll add some info to INSTALL and a line to ChangeLog.

> when you decide to take shot at it let me know 

Sure. Once I call you as @khallebal in any comment, GitHub will send you an email.

**Pull request merged**
