### PR TITLE
Create featherpad_ru.ts

### PR DESCRIPTION
**Pull request by Survolog**
Translated by Vladimir Sharonin

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks you very much. Just the first "Untitled" isn't translated; should it be "Без названия"?

**Comment by Survolog** [comment]
Yes, of cause.

**Comment by Survolog** [comment]
I'm sorry. I'll fix that later.

**Comment by tsujan** [comment]
Merged.

**Comment by tsujan** [comment]
Apparently, you have an older version of FeatherPad. I updated your translation by using Google Translate but there are still a few untranslated strings. I'd be grateful if you update your FeatherPad installation, open `featherpad_ru.ts` in Qt Linguist and translate the remaining strings. Thanks in advance!

**Pull request merged**
