### PR TITLE
Fix missing translations

### PR DESCRIPTION
**Pull request by eltonfabricio10**

### CODE REVIEW

**Comment by tsujan** [comment]
@eltonfabricio10 
It seems that GitHub has a bug. The diff (https://github.com/tsujan/FeatherPad/pull/414/files) includes `featherpad/data/help_pt_BR` but that file is already in the master branch. Also, most of `featherpad/data/translations/featherpad_pt_BR.ts` is already up-to-date; only 5 translations should be updated.

GitHub should show a merge conflict but it doesn't. I'll merge the 5 updated translations manually soon.

**Comment by eltonfabricio10** [comment]
Got it! Anyway thank you.

**Comment by tsujan** [comment]
A part of the problem was that your master branch wasn't up-to-date. But GitHub has a bug too because it should have shown a merge conflict.

Anyway, I merged your work manually, in https://github.com/tsujan/FeatherPad/commit/d6db70bc62298057758553e9d1401f5975af6150

**Comment by eltonfabricio10** [comment]
Thanks a lot!

**Pull request closed without merging**
