### PR TITLE
Fix undefined reference to socketpair for Haiku

### PR DESCRIPTION
**Pull request by khallebal**
Hi @tsujan , Is this the right place to include the -lnetwork, or do you want me to put it somewhere else?, it seems quite a few things have been added since 1.1.0.

### CODE REVIEW

**Comment by tsujan** [comment]
You are the master of Haiku; I know almost nothing about it.

If you think this is the right place and, especially, if you've tested it with the latest release of FeatherPad and encountered no problem, then I'll agree.

**Comment by tsujan** [comment]
Please also note that, now, FeatherPad uses D-Bus, instead of the old network-based method. If an OS doesn't have D-Bus, there will be no problem; just each FeatherPad window will have a separate process.

I don't know if this info is relevant to you PR though. Please tell me if it is.

**Comment by khallebal** [comment]
> You are the master of Haiku; I know almost nothing about it.
> 
> If you think this is the right place and, especially, if you've tested it with the latest release of FeatherPad and encountered no problem, then I'll agree.

Thanks, Yes i tested it against master and it works.

> I don't know if this info is relevant to your PR though. Please tell me if it is.

No, Haiku does not need or make use of D-Bus, it is disabled for FeatherPad in the CMakeList.txt, anyway thanks for the quick reply and  your support for Haiku?

**Comment by tsujan** [comment]
> it is disabled for FeatherPad in the CMakeList.txt

It isn't disabled in `CMakeList.txt`. The code takes care of it anywhere without D-Bus.

Thanks for providing the support for Haiku! If it needs any update, please don't hesitate to make PRs.

**Pull request merged**
