### PR TITLE
Update from Weblate.

### PR DESCRIPTION
**Pull request by HelixBot**

### CODE REVIEW

**Comment by tsujan** [comment]
I don't know how this is possible -- do you know Lithuanian and Danish? -- but thanks a lot!

**Comment by agaida** [comment]
welaq authored and HelixBot committed 3 days ago - lithuian
 scootergrisen authored and HelixBot committed a day ago  - danish
 Oliver Burkardt authored and HelixBot committed a day ago  - german 

so no black magic - but weblate commit pending things every hour now and send bundled pull request after some time

**Comment by tsujan** [comment]
Weblate works in strange ways but it works very well :)

**Comment by agaida** [comment]
nah - i only wrote some of the needed maintenance scripts today :P

**Comment by tsujan** [comment]
@agaida I should add their names to the Translators tab. scootergrisen is already there. welaq is [here](https://github.com/welaq). But I couldn't find Oliver Burkardt; his email or github address?

**Comment by tsujan** [comment]
Never mind, found him: https://github.com/OliverBurkardt

**Comment by agaida** [comment]
i send you a mail yesterday :p

**Comment by tsujan** [comment]
Checked it right now -- gmail's spam protection is absolute crap!!

Thanks!

**Pull request merged**
