### PR TITLE
Mac OS support

### PR DESCRIPTION
**Pull request by shlyakpavel**
This PR fixes _make install_
Everything works, including
1. Translations (with issues)
2. Docs
3. Settings, window position saving
4. Syntax highligh

Known issues:
1. Shortcuts are displayed incorrectly in settings. For example ctrl+S instead of command+S. However, cmd+S invokes save dialog properly so it's not much a problem.
image
2. Languages are not loaded correctly as the code

` lang = langs.first().split (QLatin1Char ('-')).first(); `

is an awful dirty hack. I do not know if it is okay on Linux, but it actually causes bugs on Mac and other platforms as it reports ru_RU instead of ru-RU so the string is not split and it looks for featherpad_ru_RU.qm that is not found.
3. App icon is okay on dashboard, but not okay in the package list. I will try to fix that later.
image
P. S. It is my first try in combining qmake and Mac, so some things can be really dirty

### CODE REVIEW

**Comment by shlyakpavel** [comment]
Last commit fixes language loader so Russian translation is loaded correctly out of the box on Mac

**Comment by tsujan** [comment]
> It is not Mac but clang that needs it.

Clang is already used by Qt Creator and there has been no problem.

**Comment by shlyakpavel** [comment]
@tsujan 
Qt creator uses clang to analyze the code, but not to compile it.
image
This is actually UB. Clang **does** compile the code, but it **does not** join strings.  It drops the second part instead.
I have run the debugger to check this.

**Comment by shlyakpavel** [comment]
@tsujan works fine

> What about this with mac?
> 
> ```c++
> FPTranslator.load ("featherpad_" + lang, QStringLiteral (DATADIR) + "/featherpad/translations");
> ```

Works fine! Should I use it instead?

**Comment by tsujan** [comment]
Thanks for testing it!

I've been suspicious about old-fashioned strings like `DATADIR "xxx"` in Qt for a while. Your observation shows that they should be replaced by `QStringLiteral (DATADIR) + "xxx"` (as I had to do so in `FPwin::helpDoc()`).

**Comment by tsujan** [comment]
OK, I merge this because it looks good. Please make another PR for the icon! And if you find another issue, make a third PR for it. In this way, we could know what's fixed by what.

Thanks again for the Mac support!

**Pull request merged**
