### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/tsujan/featherpad/) for Tsujan/FeatherPad.

### CODE REVIEW

**Comment by yan12125** [comment]
@mkkDr2010 @hugok79 This pull request is manually rebased due to rebase failures on Weblate. Please re-check if those changes are expected or not.

**Comment by hugok79** [comment]
All done

**Comment by hugok79** [comment]
Don't forget to put me in the credits :+1: 
Hugo Carvalho https://github.com/hugok79

**Comment by tsujan** [comment]
> Don't forget to put me in the credits

If you mean me (FeatherPad's developer), I add translators' names to the About dialog; and no, I don't forget it :)

**Comment by hugok79** [comment]
Thank you

**Comment by tsujan** [comment]
Thank *you* and @mkkDr2010 for your translations!

**Comment by tsujan** [comment]
@yan12125, @stefonarch 

It seems that Weblate can't detect corrupted ts files. The Bulgarian ts file caused FTBFS. I fixed it manually.

We should be more cautions in LXQt and compile the sources after merging Weblate PRs once in a while.

**Comment by stefonarch** [comment]
I noticed that in in the merge conflict but didn't think further, so not sure where this corruption happened - weblate usually spites parse errors for everything (the html file for screengrab among them) and stops. Do you have the original wrong file still?
There were an upload for *_bg.ts in every repo in the last days, will recompile  all.

**Comment by tsujan** [comment]
As far as the xml syntax was concerned, the file was OK. The corruption was about the "ts" syntax, which Qt Linguist found and I  fixed manually: there was an extra `<numerusform></numerusform>`. You could find it here: https://github.com/tsujan/FeatherPad/commit/bc3f960ddb5698db1a8b2ca15b25dba8aa51dcea (search for "featherpad_bg.ts" in the commit).

**Comment by stefonarch** [comment]
I'm thinking about a private hidden project with restricted access for testing stuff, I saw this possibility.

**Comment by tsujan** [comment]
Doesn't Travis do that?

**Comment by yan12125** [comment]
Oops seems a error from a manual rebase. I'm not sure if there is an option in Weblate, but CIs like Travis should work.

**Comment by stefonarch** [comment]
FYI I recompiled all, no fails.

**Comment by tsujan** [comment]
> FYI I recompiled all, no fails.

It should have taken a lot of time from you! I think and hope such problems will be very rare.

**Comment by stefonarch** [comment]
> It should have taken a lot of time from you

No, it's a just script for all folders, l checks for updates, pull and compile, in 15-20 minutes it's done.

**Comment by stefonarch** [comment]
Here is another file with errors (new paragraph), doesn't harm compiling.
https://raw.githubusercontent.com/lxqt/lxqt-sudo/bef60d8caa7420a3f0ceaeb64a91fbdb268c7b77/translations/lxqt-sudo_bg.ts
```

 <message>
        <location filename="../sudo.cpp" line="376"/>
        <source>Child &apos;%1&apos; process failed!
%2</source>
        <translation>Дъщерният процес &apos;%1&apos;пропадна!
%2</translation>
    </message>
```
I think I can correct it in the commit. 
@mkkDr2010 Please always double check in the GUI of QtLinguist before uploading that there is all green, those 2 errors are shown as yellow.

**Comment by mkkDr2010** [comment]
Is that mess from my translations? I am sorry, but I’m not familiar with that kind of errors. I just uploaded the translated files and I there weren’t problems on my system. 
With regards 





Am Freitag, Dezember 11, 2020, 1:29 PM schrieb Standreas <notifications@github.com>:




Here is another file with errors (new paragraph), doesn't harm compiling.
https://raw.githubusercontent.com/lxqt/lxqt-sudo/bef60d8caa7420a3f0ceaeb64a91fbdb268c7b77/translations/lxqt-sudo_bg.ts

 <message>
        <location filename="../sudo.cpp" line="376"/>
        <source>Child &apos;%1&apos; process failed!
%2</source>
        <translation>Дъщерният процес &apos;%1&apos;пропадна!
%2</translation>
    </message>

I think I can correct it in the commit.
@mkkDr2010 Please always double check in the GUI of QtLinguist before uploading that there is all green, those 2 errors are shown as yellow.

**Comment by mkkDr2010** [comment]
What exactly caused the problem? What should I be aware from?



Am Freitag, Dezember 11, 2020, 1:29 PM schrieb Standreas <notifications@github.com>:




Here is another file with errors (new paragraph), doesn't harm compiling.
https://raw.githubusercontent.com/lxqt/lxqt-sudo/bef60d8caa7420a3f0ceaeb64a91fbdb268c7b77/translations/lxqt-sudo_bg.ts

 <message>
        <location filename="../sudo.cpp" line="376"/>
        <source>Child &apos;%1&apos; process failed!
%2</source>
        <translation>Дъщерният процес &apos;%1&apos;пропадна!
%2</translation>
    </message>

I think I can correct it in the commit.
@mkkDr2010 Please always double check in the GUI of QtLinguist before uploading that there is all green, those 2 errors are shown as yellow.

**Comment by tsujan** [comment]
@mkkDr2010 
Simply use Qt Linguist to see if your translations are OK. Your translations are very appreciated; this is about syntax errors.

**Comment by hugok79** [comment]
@mkkDr2010 I think you can also download the translation file as gettext PO and use the Poedit to translate it. IMHO, Poedit is more simple to use.

**Comment by stefonarch** [comment]
No need to download anything for correcting those errors, no one of the files is causing compile errors.
 Just use weblate https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-sudo/bg/ click the failed checks and some can be corrected automatically. You can check all your translations in this way.
 
schermata-15-24-21

**Comment by mkkDr2010** [comment]
I will try it.But in lxqt there left not much to translate in Bulgarian



Am Freitag, Dezember 11, 2020, 3:01 PM schrieb Hugo Carvalho <notifications@github.com>:




@mkkDr2010 I think you can also download the translation file as gettext PO and use the Poedit to translate it. IMHO, Poedit is more simple to use.

**Comment by mkkDr2010** [comment]
Those are the errors messages. Most of them I left with purpose untranslated.


Gesendet von Yahoo Mail für iPhone


Am Freitag, Dezember 11, 2020, 3:25 PM schrieb Standreas <notifications@github.com>:




No need to download anything for correcting those errors, no one of the files is causing compile errors.
Just use weblate https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-sudo/bg/ click the failed checks and some can be corrected automatically. You can check all your translations in this way.

**Comment by mkkDr2010** [comment]
By the way, I was thinking over to translate lxqt-connman applet but I read an old issue from you about problems with compiling and building the application. I tried it with git code too, and became errors by make. Although the building from aur went without any errors (there are some patches too). Is the application depreciated? I find the cmst more complex and informative. 
     Am Freitag, 11. Dezember 2020, 15:25:21 MEZ hat Standreas <notifications@github.com> Folgendes geschrieben:  
 
 


No need to download anything for correcting those errors, no one of the files is causing compile errors.
Just use weblate https://translate.lxqt-project.org/projects/lxqt-configuration/lxqt-sudo/bg/ click the failed checks and some can be corrected automatically. You can check all your translations in this way.

**Comment by tsujan** [comment]
@mkkDr2010

LXQt has a "Discussion" section now. You could add your questions to "Q&A".

This repository belongs to FeatherPad, which doesn't belong to LXQt.

**Pull request merged**
