### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/tsujan/featherpad/) for Tsujan/FeatherPad.

### CODE REVIEW

**Comment by tsujan** [comment]
@stefonarch, do you know why the French translator changed `MAJ` to `Shift`, `Haut` to `Up`, etc.? I think that's incorrect. The shortcuts work as they are.

**Comment by stefonarch** [comment]
There is an info box about shortcuts translations in weblate which says:

>**Keyboard shortcuts translations:** In some languages a wrong translation disables the corresponding shortcut. 
>Frequent examples are **canc, Alt, Shift, Home, Up/Down** and else.
>A working shortcut will be displayed in the translated GUI right to the menu item. Cloning source text should always work.

A translator should test it IMO it: if it's visible it's ok.
 I noticed yesterday that he removed or [changed some accelerators](https://github.com/lxqt/qterminal/commit/2bea9f4a9f5170d222ffce0ec9ea953b03ef4a39#diff-758244a6addbd744a79cfe7da59ff7617a69671f09cd04fe36b18f2a4ad603c8) in qterminal, but I noticed that some of them aren't displayed in the GUI and merged it, it a thing to check but not urgent as it doesn't any harm.

**Comment by tsujan** [comment]
> I noticed yesterday that he removed or changed some accelerators in qterminal, 

Yes, he did that here too.

As for shortcuts of the French localization, all of them are OK without this PR. I guess he hasn't installed Qt5 translations.

The Hebrew part of this PR also has a problem that I fixed before. Qt complained about plurals when I updated translations and I removed exactly the lines that are added here again.

I have to close this PR. Will that cause a problem at Weblate? Or can it be done from Weblate instaead?

**Comment by tsujan** [comment]
This is the `lupdate`'s message for the change that's done here to the Hebrew message:

```
Updating 'data/translations/featherpad_he.ts'...                                                                       
    Found 432 source text(s) (0 new and 432 already existing)                                                          
Removed plural forms as the target language has less forms.                                                            
```

`lupdate` simply removes those lines.

Tonight, I want to release FeatherPad 0.18.0.

**Comment by stefonarch** [comment]
Looks like we're going to have a rebase failure at the end :)
If you close it weblate will force-push it again forever until I reset last changes, when there were those pt_PT files I had to do so, so no problem if you close it.

I contacted him but forgot to mention the removed accelerators.

**Comment by tsujan** [comment]
> so no problem if you close it.

OK. I'm closing it.

It's hard to check all translations -- I know how difficult your job is at LXQt.

BTW, when you find the time, ask him to add his name/pseudonym or GitHub address -- something I can add to Translators list.

**Comment by stefonarch** [comment]
Got a response and mentioned the accelerators, he's sorry and will undo it, so it should be corrected in the next PR.
BTW I noticed only now that weblate has apparently no check for accelerators missing (as QtLinguist has), I didn't find anything useful how to implement it ( "weblate.checks.format.CFormatCheck" ? )

Enabled checks: https://translate.lxqt-project.org/checks/?project=tsujan

@yan12125 any idea?

**Comment by tsujan** [comment]
> BTW I noticed only now that weblate has apparently no check for accelerators missing

It's good to add them in translations but, IMO, it isn't urgent. The translator should be cautious to not add an accelerator twice in a menu and that may not be easy without using extra tools (like Qt Designer).

**Comment by tsujan** [comment]
Another thing about accelerators:

Some languages can't have them easily. They may need to use something like (A) in front of the text. Too many accelerators might damage GUI readability in such cases but @yan12125 knows these things much better than I do.

**Comment by yan12125** [comment]
> I noticed only now that weblate has apparently no check for accelerators missing (as QtLinguist has), I didn't find anything useful how to implement it ( "weblate.checks.format.CFormatCheck" ? )

No idea either. Maybe a missing feature from Weblate.

> Some languages can't have them easily. They may need to use something like (A) in front of the text. Too many accelerators might damage GUI readability in such cases

Yep that's the case for languages that don't use (a subset of) alphabet like Chinese (zh_*), Japanese (ja) and so on. I'm not sure what others think, but I'm accustomed to texts like (A) everywhere.

**Comment by tsujan** [comment]
> Yep that's the case for languages that don't use (a subset of) alphabet 

You're right. I wasn't sure about Arabic, Hebrew and Persian but it seems they're like English in this regard. Qt has really covered all cases.

**Pull request closed without merging**
