### PR TITLE
WIP: Replace help and translations to the app bundle

### PR DESCRIPTION
**Pull request by shlyakpavel**
Now:
Everything works fine, no regressions :)
But:
- the way I locate app bundle is incorrect
- the way I locate help files is even worse
Approach: not to store paths in the binary to make the app bundle portable.

### CODE REVIEW

**Comment by shlyakpavel** [comment]
To make it clear
Before merging this PR the program could not find translations unless being installed. Now it can load translations being built and run in any folder

**Comment by tsujan** [comment]
Thanks you very much!

I had two questions:

(1) I know it's helpful on Haiku. Is it on Mac too?

(2) Doesn't it affect *installed* translations on Mac?

**Comment by shlyakpavel** [comment]
1. As you can see in the code I didn't touch Haiku
2. The translations were installed into the bundle on `make install`. Now they are embedded into the bundle by qmake before installation. I'm afraid I do not understand the question

**Comment by tsujan** [comment]
> As you can see in the code I didn't touch Haiku

I know. I meant Haiku needed such a thing because of its structure but I didn't think Mac might need it too. Hence mentioning Haiku.

> I'm afraid I do not understand the question

My question was about the lack of regression; now I see that you'd mentioned it in the first comment.

**Comment by shlyakpavel** [comment]
@tsujan I'm stuck with make and paths. Is there any *correct* way to get qm files path? Currently it works only with qt creator, but not `make` in terminal (something related to environment)

**Comment by tsujan** [comment]
> Is there any correct way to get qm files path?

I have no idea.

> I am really starting to hate qmake...

In past, I might felt angry sometimes ;) but always found a way.

**Comment by shlyakpavel** [comment]
@tsujan why do you prefer qmake over cmake? It seems to be much less problematic, especially for cross-platform apps

**Comment by tsujan** [comment]
> @tsujan why do you prefer qmake over cmake?

It's (1) easier to use and (2) more backward compatible. For example, Kvantum has both but, months ago, I had to edit its cmake file because of recent changes in cmake. I haven't encountered such problems with qmake at all.

BTW, I've got angry at cmake more than qmake ;)

**Comment by shlyakpavel** [comment]
@tsujan 
Found a project that does exactly what I want to :)
https://github.com/wereturtle/ghostwriter/blob/master/ghostwriter.pro

**Comment by tsujan** [comment]
> Found a project that does exactly what I want to :)

Great! You see? There's always a way with Qt/qmake ;)

**Comment by agaida** [comment]
re qmake - from the packge maintainer side qmake should die :sunglasses: it's pain in the arse.

**Comment by tsujan** [comment]
> from the packge maintainer side qmake should die sunglasses it's pain in the arse.

I don't know about details of maintenance but I remember -- from times when I was a Debian user -- that making deb packages with qmake was easy. What's the drawback?

**Comment by tsujan** [comment]
And glad you're back -- and I hope you'll remain...

**Comment by tsujan** [comment]
Last year, something terrible hit me and the inevitable tragedy happened. Luckily, I remembered my childhood ability of letting go. It comes back with old age ;)

**Comment by agaida** [comment]
re drawback - try to make cross-builds with qmake, override some settings for different architectures or simple out of the tree builds - it's a major fuckup. Even KDE consider it and will switch to meson for some projects afaik

**Comment by tsujan** [comment]
> ... some settings for different architectures...

Hadn't thought about it. Will add cmake support to both projects later -- a pain in the ass to me ;)

**Comment by tsujan** [comment]
> i might change my mind

Adding cmake support is very boring to me but, once done, its maintenance will be easy. Kvantum has it and it didn't kill me.

**Comment by shlyakpavel** [comment]
@tsujan huh, no idea. Will test it later :)

**Comment by tsujan** [comment]
@shlyakpavel Never mind! It was about the latest commit and the new doc DND feature. I'll make a small change in it to recognize FN docs only based on their extension; it should work everywhere.

**Comment by shlyakpavel** [comment]
I have tried Haiku :)
Bundling seems to be quite the same problem there.
Found some bugs on this PR, please do not merge it until I say it's done :)
As for mime types - they are still not tested

**Comment by tsujan** [comment]
About qmake:

It seems that qmake has no future: they want to abandon it in Qt6. I have about one and a half year to replace it with cmake ;) but will do so with V0.9.5, preserving qmake too, until it isn't usable.

**Comment by tsujan** [comment]
UPDATE:
cmake support added. It works well under Linux. For Haiku OS and macOS, I copied what was in the pro file; so, theoretically it should be OK for those OS's but tests would be very appreciated.

**Comment by shlyakpavel** [comment]
As soon as qmake cannot process hunspell correctly anyway, I'll be switching to cmake. This PR has no sense anymore.

**Pull request closed without merging**
