### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/tsujan/featherpad/) for Tsujan/FeatherPad.

### CODE REVIEW

**Comment by tsujan** [comment]
@stefonarch 
This is a vicious circle (see https://github.com/tsujan/FeatherPad/pull/500 and https://github.com/tsujan/FeatherPad/pull/495). Does Weblate do it automatically? If so, can it be stopped in Weblate?

**Comment by stefonarch** [comment]
It looks like done by @yarons :
https://translate.lxqt-project.org/projects/tsujan/featherpad/he/#history
I did a reset in weblate but no idea why it didn't reset this commit to 0 files changed. Just close this PR atm.

**Comment by tsujan** [comment]
Thanks. I hope it won't change again.

@yarons, please don't add those plural forms (see https://github.com/tsujan/FeatherPad/pull/495).

**Comment by yarons** [comment]
@tsujan Completely forgot about that, is there a way to control the plural forms per string?

**Comment by tsujan** [comment]
> Completely forgot about that

It's OK.

> is there a way to control the plural forms per string?

If you used Qt Linguist, you'd see the correct number of plural forms per string — or, at least, what Qt considers as the correct number (which is really correct in this case). It seems to me that Weblate may have a problem in this regard.

Qt Linguist shows that your Hebrew translation of FeatherPad is complete. In future, more strings might be added but please don't change this one. Thanks for your complete translation!

**Pull request closed without merging**
