### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/tsujan/featherpad/) for Tsujan/FeatherPad.

### CODE REVIEW

**Comment by stefonarch** [comment]
For the Hebrew I'v no clue @yarons ?
For the other probably he forgot to undo it, me or you could  do it in weblate but we'll appear as french translator, I'd wait for now merging.

**Comment by yarons** [comment]
@tsujan hey guys, yes, we initiated a change with the Hebrew plural forms to reflect the actual way we speak (we don't say two hours we say something like duhours in a single word, same goes for month, year and several others).

Thank you.

**Comment by tsujan** [comment]
@yarons,
Qt removes the changes you made here and shows the message I mentioned at https://github.com/tsujan/FeatherPad/pull/495#issuecomment-794326086 because the same string is repeated three times.

**Comment by stefonarch** [comment]
I think actually there is no way from filecount to let herbrew translation know if it were 2 or 10, 20, 30 or else (if I got it right)
 It's just one or more - always.

**Comment by tsujan** [comment]
@stefonarch 
It isn't about the number. Some languages can have 3 plural forms. In this case, Qt sees it as an error and removes it. That has happened twice. If I merge it, it'll be reversed by Qt automatically as soon as I update translations.

I can merge it and then reverse `Del` and Hebrew plurals, or I can close it and remove `type="unfinished"` from the French translation myself.

**Comment by tsujan** [comment]
Oh, I found where the problem is :)

The translatable string is "%Ln Replacements" (I've separated the plural form in the code). The translations are `החלפה אחת` (One replacement) and there cases of `%Ln החלפות` (%Ln Replacements). The first translation is incorrect. If Hebrew distinguishes between 2 and more (or 2, 3 and more, etc.), those plural forms should have been used, not the singular form.

**Comment by yarons** [comment]
@tsujan I don't understand.

In some cases Hebrew uses singular and plural (most cases) the rare cases are the ones I've mentioned (hours, days, weeks, etc.), Replacements doesn't require the additional plural forms, AFAICT choosing a plural form for a specific string is only possible with XLIFF, gettext doesn't support that kind of feature.

**Comment by tsujan** [comment]
@yarons 
First, thanks for your complete Hebrew translation and sorry for my ignorance about Hebrew! I started to learn it many years ago but didn't find the required time :(

Here, I only described Qt's behavior; otherwise, I know that you master Hebrew. Qt Linguist has only *one place* for the Plural form of "Replacements" in Hebrew and Qt removes the other two instances that you've added here.

In the code, "No Replacement", "One Replacement" and "%Ln Replacements" are intentionally separated from each other. You've correctly translated the first two string as `אין החלפה` and `החלפה אחת` respectively. You've also correctly translated the third string: although it's is *purely plural*, `החלפה אחת` can be added for the probable singular form (someone might change the code in future). Qt's complaint is only about the two extra instances of `%Ln החלפות`. According to Qt, one is enough.

If Qt is wrong in that regard, it should be reported to Qt bug tracker. But, looking at the identical plural forms in Hebrew (that you've added), I think Qt may not be wrong.

**Comment by yarons** [comment]
@tsujan thank you for trying to learn Hebrew, it's awesome :)

Yeah, I understood your way and I confirmed before that in that case we can lose the redundant identical plural forms only if it means that it won't affect other strings that do need that (such as the terms I've mentioned earlier).

Thank you :)

**Comment by tsujan** [comment]
> Hebrew, it's awesome

Yes, someday, I might try again :)

Since "Replacements" doesn't require the additional plural forms, let's use only one and silence Qt's warning.

**Comment by stefonarch** [comment]
I wrote an email to the french translator about those spaces he starts to add before : and ! - stumbled upon those in lxqt-sudo just now.

```
 <source>Tab position: </source>
      -  <translation>Emplacement des onglets: </translation>
       * <translation>Emplacement des onglets : </translation>
```

**Comment by tsujan** [comment]
> I wrote an email to the french translator about those spaces he starts to add before : and ! 

I may be wrong but I think they're correct in French.

**Comment by tsujan** [comment]
@stefonarch 
I checked it. In French, exclamation marks, (semi-)colons, and question marks need a space before them.

**Comment by stefonarch** [comment]
Ok, I first asked my daughter which lived in Paris and studied french, she said no...

**Comment by stefonarch** [comment]
Got his response, he said weblate marked them:
https://docs.weblate.org/en/weblate-4.2.1/user/checks.html#check-punctuation-spacing

I tested and there is the button "fix string" which inserts a non breakable space.

**Comment by tsujan** [comment]
French Punctuation: https://iwillteachyoualanguage.com/learn/french/french-tips/french-punctuation

**Comment by tsujan** [comment]
@stefonarch 
BTW, please tell me when I can merge this PR -- I could correct `Del` manually in French and Qt will remove the redundant Hebrew strings.

**Comment by stefonarch** [comment]
As for me you can merge it, I thought you already did.
I think just correct after merging the Del string.

**Comment by tsujan** [comment]
Fixed the problems in https://github.com/tsujan/FeatherPad/commit/af0c0a3aa4987f41006c6f88e5802806f2500834 (Qt did the second one).

**Pull request merged**
