### PR TITLE
Update featherpad.desktop

### PR DESCRIPTION
**Pull request by stefonarch**

### CODE REVIEW

**Comment by tsujan** [comment]
Also below `[Desktop Action new-window]`, for Italian?

**Comment by stefonarch** [comment]
Didn't scroll down :)
-standalone is hard to translate, better leave it english

**Comment by tsujan** [comment]
Thanks a lot!

**Comment by tsujan** [comment]
> -standalone is hard to translate, better leave it english

This time, *I* didn't scroll down ;)

**Pull request merged**
