### PR TITLE
Update from Weblate.

### PR DESCRIPTION
**Pull request by lxdeadmin**

### CODE REVIEW

**Comment by agaida** [comment]
Please don't merge right now. Thanks

**Comment by agaida** [comment]
Please add in Integrations & services the weblate service:

**Comment by tsujan** [comment]
Isn't "mit riesigen Zeilen" correct.

> Please add in Integrations & services the weblate service:

Where? Can't find "Integrations & services" anywhere.

**Comment by agaida** [comment]
'riesiegen' should be 'riesigen', but i guess 'sehr langen' is better - even better would be "with huge lines
(> XY k)" or so

**Comment by agaida** [comment]
it is in repo settings: https://github.com/tsujan/FeatherPad/settings/installations

**Comment by tsujan** [comment]
> it is in repo settings

Thanks! Did as to told:

screengrab-20180507-231140

**Comment by tsujan** [comment]
> 'riesiegen' should be 'riesigen'

Ha ha, I'd written it correctly; my German isn't so bad ;)

**Comment by tsujan** [comment]
> even better would be "with huge lines (> XY k)" or so

A huge line means a line with more than 500,000 characters. I think no reasonable text file should be so but didn't want to bother users with details.

Kate does an annoying trick with such files: it first shows a message with files whose lines have much less characters and if the user accepts the risk, it either hangs after eating up the CPU or disables scrolling over such lines.

**Comment by agaida** [comment]
do you ever opend a database dump - or even better: large minified js files? \/me run and hide

**Comment by tsujan** [comment]
Not related to translation (*sehr lang* is good):

A relatively small file can have huge lines in it. I don't remember where I encountered such a file -- mhtml? -- but they aren't for editing.

FeatherPad has another safeguard too: if the number of characters in a single line of a CSS file is more than 50,000 (but less than 500,000), that line won't have syntax highlighting. Apart from these cases, run-and-hide is the best strategy.

**Comment by tsujan** [comment]
Can I merge this?

**Comment by agaida** [comment]
please

**Pull request merged**
