### PR TITLE
Remove the Spanish country specific translation

### PR DESCRIPTION
**Pull request by micrococo**
Just use the generic Spanish language file, there's no need for a country specific file.

### CODE REVIEW

**Comment by tsujan** [comment]
Thanks! The thought occurred to me that `es_ES` may not be needed but wasn't sure.

Do you have a plan to add further commits to this PR?

**Comment by micrococo** [comment]
Hi. I think it's all done, no more commits expected for this PR.

**Comment by tsujan** [comment]
> I mean, ¿the deleted file is also deleted there?

Yes, it is.

**Comment by tsujan** [comment]
I mean it should be deleted but if not, it'll be about a bug in Weblate.

**Pull request merged**
