### PR TITLE
Handle haxe language files as JS to get syntax highlighting

### PR DESCRIPTION
**Pull request by urnenfeld**
Hello,

I was to create an Issue to have syntax highlighting in **haxe** language.
The **JS** highlighting works fine for **haxe** language, therefore here is a _hacky_ proposal which worked for me.

If you could detail the proper steps I can remake the pull request.

Regards

### CODE REVIEW

**Comment by tsujan** [comment]
Interesting! I hadn't heard of `haxe`.

Please let me to investigate `haxe` and find its relation to JS. It may take some time (I'm busy with other codes now) but I'll do it and will keep this open until then. Thanks!

**Comment by urnenfeld** [comment]
Another option would be to be able to choose the highlighting explicitly.

I have found myself many times in situations like open a scons file without syn. high. while there is just python code inside... same for the hundreds of xml and yaml variations.

In any case, I saw the related code is shared among sone files, if you can give some hints on how a proper implementation should be, I can take a look.

**Comment by tsujan** [comment]
> I have found myself many times in situations like open a scons file without syn. high.

Oh, FeatherPad supports syntax highlighting only for languages that are listed in its language button (which will be shown if `Preferences → Text → Support syntax override` is checked) plus a few others.

Adding languages isn't a trivial work at all. Actually, highlighting the syntax of some of the supported languages has been like a nightmare to me (I've heard similar descriptions by authors of syntax highlighting libraries -- FeatherPad does it on its own).

> ... same for the hundreds of xml and yaml variations.

FeatherPad doesn't support mixed languages, except for JS and CSS inside HTML. Yaml code blocks are only highlighted as code blocks.

> if you can give some hints on how a proper implementation should be, I can take a look.

If `haxe` needs a syntax highlighting different from that of JS, it might take a lot of work. The most complicated source files in FeatherPad are `highlighter.cpp` and its related files. But if JS syntax highlighting is enough for `haxe`, it'll be easy.

**Comment by tsujan** [comment]
> Another option would be to be able to choose the highlighting explicitly.

Oh, it's already supported, as mentioned above (Preferences → Text → Support syntax override).

**Comment by urnenfeld** [comment]
> Oh, it's already supported, as mentioned above (Preferences → Text → Support syntax override).

Another miss from my side. This feature makes that the code changed in the PR, is at this point just saving me 2 clicks for making the override :smile:

> If haxe needs a syntax highlighting different from that of JS, it might take a lot of work

I am not an `haxe` expert, but have been inspecting code all the day(with the patch in this PR) and the `JS` highlighting is doing fine for `haxe`. Coincidence maybe, in fact I expected the `cpp` highlighter render better results. The same set of rules/regex could be applied... (but of course not in the way it is done in this PR)

> FeatherPad doesn't support mixed languages, except for JS and CSS inside HTML. Yaml code blocks are only highlighted as code blocks.

Oh I meant for example you have a file *.arxml which is infact an xml, but the editor will not make SH because is unaware of the extension. But again, the *syntax override* functionality solves this problem.

**Comment by tsujan** [comment]
> have been inspecting code all the day(with the patch in this PR) and the JS highlighting is doing fine for haxe. 

That's very good news. I also saw 5 or 6 haxe samples and JS worked fine. I'll search the Internet for a few days...

> Oh I meant for example you have a file *.arxml which is infact an xml, but the editor will not make SH because is unaware of the extension.

Yes, I first misread your second comment. Later, when I saw that you'd asked about overriding, I saw my mistake ;)

BTW, if you show the menu by clicking the override button and type a part of a language name, it'll be selected in the menu and you could choose it by pressing Enter -- I mean you don't need to search for it.

**Comment by tsujan** [comment]
OK, let's have a minimal Haxe support in this way. JS syntax highlighting may be more than what Haxe needs but all code snippets I found were covered -- there were a few additional keywords but nothing important.

Thanks again!

**Pull request merged**
