### PR TITLE
Update from Weblate.

### PR DESCRIPTION
**Pull request by lxdeadmin**

### CODE REVIEW

**Comment by tsujan** [comment]
Please tell me when it's ready.

BTW, with the next commit, a short text will be added: "Thick text cursor".

**Comment by agaida** [comment]
ok, will be fetched automagicall with the next commit in github. These single commits sucks a bit, i have not triggered any commit - only approved some Strings after reviewing them again. So i would suggest to squash that.

**Comment by tsujan** [comment]
Thanks!

**Comment by tsujan** [comment]
Apart from correcting mistakes, you were very meticulous here. I know it should have been hard and appreciate it.

**Comment by agaida** [comment]
There are a few very good reasons for:
* there is a packaging bug in featherpad debian - i underestimated the the translations so i don't havn't done a -l10n package. That means i have to live with the translations every day a few hours :P 
* testing weblate
* play with and extend our weblate installation a bit - and with a application that i use every day that makes really sense :D

**Comment by agaida** [comment]
cool, the resync to weblate goes totally wrong with the squashed commit (as expected) - no problem to do this by hand, but i guess it is a common use case so i should talk with the developer about it - or maybe write a script to circumvent it

**Comment by tsujan** [comment]
My knowledge of those things is very poor.

**Comment by agaida** [comment]
simply plain git

**Pull request merged**
