### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by LXQtBot**
Translations update from [Weblate](https://translate.lxqt-project.org/projects/tsujan/featherpad/) for Tsujan/FeatherPad.

### CODE REVIEW

**Comment by Vistaus** [comment]
@tsujan In FeatherNotes, “Recently opened” is used and I find it better anyway as all other software, at least in Dutch, uses “Recently opened”.

**Comment by tsujan** [comment]
FeatherNotes is very different.

With FeatherPad, the user can choose between "recently modified" and "recently opened" in Preferences → Files. They are totally different functionalities: opening vs. modifying. The current Dutch translation is correct, while this commit would introduce a bug in the GUI.

**Comment by Vistaus** [comment]
Oh, I see. I missed that setting. I will revert this then. I'm sorry for the trouble I caused.

**Comment by tsujan** [comment]
No need to be sorry; these things happen. Your translations are among the best and most complete. I really appreciate your work.

**Comment by Vistaus** [comment]
That's nice to hear, thanks! 🙂

**Pull request merged**
