### PR TITLE
Implemented tab-insert-spaces feature (like in other editors)

### PR DESCRIPTION
**Pull request by GoodNike**

### CODE REVIEW

**Comment by tsujan** [comment]
Thank you very much for trying to make FeatherPad better but, as I mentioned in https://github.com/tsujan/FeatherPad/issues/233, I prefer to have both soft and ordinary tabulations (Ctrl+TAB and TAB) beside each other for practical reasons. The "either-or" situation of other text editors is not acceptable.

Please also take a look at Help (Ctrl+H)!

**Comment by GoodNike** [comment]
Thanks for fast reply!
Maybe add an option to change default behaviour for Ctrl+TAB and TAB (TAB to be spaces Ctrl+TAB to be tabs)?

**Comment by tsujan** [comment]
There's no reason to do that and it would be weird.

**Comment by tallesl** [comment]
> There's no reason to do that and it would be weird.

How come? Such option is pretty much ubiquitous in text editors, and the lack of it is the sole reason I have to find a substitute for featherpad while using lubuntu.

**Comment by tsujan** [comment]
> ... the sole reason I have to find a substitute for featherpad while using lubuntu.

And that should matter to me?! Like any open-source project, FeatherPad is a work that its author has shared with others freely. You're also free to use or not to use it.

**Comment by tallesl** [comment]
I'm just endorsing the work that the OP has done.

Like any comment on an open-source project issue, it's an opinion that its author has shared with others freely. You're also free to use or not use it.

**Comment by zephyr707** [comment]
> And that should matter to me?!

yes.

**Comment by janEntikan** [comment]
It is my opinion that this is an absolutely -insane- design choice. I'm uninstalling featherpad now. I am not going to constantly press ctrl-tab.

**Comment by tsujan** [comment]
Locking the page, to prevent more nonsense...

**Pull request closed without merging**
